# Generated by Django 4.0.5 on 2022-06-05 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anonce', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='typeAnime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.type', verbose_name='Тип'),
        ),
    ]
