# Generated by Django 4.0.5 on 2022-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_status_alter_anime_typeanime'),
        ('anime4nik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='anime',
            field=models.ManyToManyField(to='anime.anime'),
        ),
    ]
